<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\CharacterAdminController;
use App\Http\Controllers\Admin\CharacterLogAdminController;
use App\Http\Controllers\Admin\CityAdminController;
use App\Http\Controllers\Admin\FactionAdminController;
use App\Http\Controllers\Admin\GameJobAdminController;
use App\Http\Controllers\Admin\ItemAdminController;
use App\Http\Controllers\Admin\LicenceAdminController;
use App\Http\Controllers\Admin\LocationAdminController;
use App\Http\Controllers\Admin\MapMarkerAdminController;
use App\Http\Controllers\Admin\ModeratorAdminController;
use App\Http\Controllers\Admin\NationRequisitionAdminController;
use App\Http\Controllers\Admin\NationLogAdminController;
use App\Http\Controllers\Admin\PermissionAdminController;
use App\Http\Controllers\Admin\GameMasterAdminController;
use App\Http\Controllers\Admin\RefundAdminController;
use App\Http\Controllers\Admin\StockMarketAdminController;
use App\Http\Controllers\Admin\SkirmishAdminController;
use App\Http\Controllers\Admin\UnitAdminController;
use App\Http\Controllers\Admin\DiscordWebhookAdminController;
use App\Http\Controllers\Admin\DiscordManagementController;
use App\Http\Controllers\Admin\UserAdminController;
use App\Http\Controllers\BannedAccountController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterStateController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\DiscordLinkController;
use App\Http\Controllers\FactionController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\GlobalChatController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\LeaderboardController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\MarketController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\NationController;
use App\Http\Controllers\NationRequisitionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PresenceController;
use App\Http\Controllers\PublicDiscordRosterController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\WorkController;
use Illuminate\Support\Facades\Route;

Route::get('/', [GameController::class, 'home'])->name('home');
Route::get('/discord-roster/{nation}', [PublicDiscordRosterController::class, 'show'])->name('discord-roster.show');

Route::middleware(['auth', 'not_banned'])->group(function () {
    Route::get('/dashboard', [GameController::class, 'dashboard'])->name('dashboard');
    Route::post('/presence/ping', [PresenceController::class, 'store'])->name('presence.store');

    Route::get('/factions', [FactionController::class, 'index'])->name('factions.index');
    Route::post('/factions', [FactionController::class, 'store'])->name('factions.store');

    Route::get('/character/create', [CharacterController::class, 'create'])->name('characters.create');
    Route::post('/character', [CharacterController::class, 'store'])->name('characters.store');

    Route::middleware('character')->group(function () {
        Route::get('/lobby', [GameController::class, 'lobby'])->name('lobby');
        Route::get('/character/state', [CharacterStateController::class, 'show'])->name('characters.state');
        Route::get('/cities/{city:slug}', [CityController::class, 'show'])->name('cities.show');
        Route::get('/locations/{location}', [LocationController::class, 'show'])->name('locations.show');
        Route::post('/locations/{location}/messages', [MessageController::class, 'store'])->name('messages.store');
        Route::get('/chat/state', [ChatController::class, 'state'])->name('chat.state');
        Route::post('/chat/send', [ChatController::class, 'store'])->name('chat.send');
        Route::get('/chat/global', [GlobalChatController::class, 'index'])->name('chat.global.index');
        Route::post('/chat/global', [GlobalChatController::class, 'store'])->name('chat.global.store');
        Route::post('/locations/{location}/work', [WorkController::class, 'store'])->name('work.store');
        Route::get('/store', [StoreController::class, 'index'])->name('store.index');
        Route::get('/license-center', [StoreController::class, 'licences'])->name('store.licences');
        Route::post('/store/purchase', [StoreController::class, 'purchase'])->name('store.purchase');
        Route::get('/profile/game', [CharacterController::class, 'show'])->name('characters.show');
        Route::get('/profile/inventory', [InventoryController::class, 'index'])->name('inventory.index');
        Route::get('/home', [HomeController::class, 'index'])->name('home.index');
        Route::post('/home/tiles/clear', [HomeController::class, 'clearTile'])->name('home.tiles.clear');
        Route::post('/home/buildings/place', [HomeController::class, 'placeBuilding'])->name('home.buildings.place');
        Route::patch('/home/buildings/{characterLandBuilding}/move', [HomeController::class, 'moveBuilding'])->name('home.buildings.move');
        Route::delete('/home/buildings/{characterLandBuilding}', [HomeController::class, 'destroyBuilding'])->name('home.buildings.destroy');
        Route::post('/home/sleep', [HomeController::class, 'sleep'])->name('home.sleep');
        Route::get('/jobs', [JobController::class, 'index'])->name('jobs.index');
        Route::post('/jobs/{gameJob}', [JobController::class, 'store'])->name('jobs.store');
        Route::get('/nation', [NationController::class, 'index'])->name('nation.index');
        Route::post('/nation/donate', [NationController::class, 'donate'])->name('nation.donate');
        Route::patch('/nation/members/{character}/rank', [NationController::class, 'updateRank'])->name('nation.members.update-rank');
        Route::get('/nation/requisitions', [NationRequisitionController::class, 'index'])->name('nation.requisitions.index');
        Route::post('/nation/requisitions', [NationRequisitionController::class, 'store'])->name('nation.requisitions.store');
        Route::get('/leaderboards', [LeaderboardController::class, 'index'])->name('leaderboards.index');
        Route::get('/stocks', [MarketController::class, 'index'])->name('market.index');
        Route::get('/stocks/state', [MarketController::class, 'state'])->name('market.state');
        Route::post('/stocks/{company}/buy', [MarketController::class, 'buy'])->name('market.buy');
        Route::post('/stocks/{company}/sell', [MarketController::class, 'sell'])->name('market.sell');
    });

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::post('/profile/discord-link', [DiscordLinkController::class, 'store'])->name('profile.discord-link.store');
    Route::delete('/profile/discord-link', [DiscordLinkController::class, 'destroy'])->name('profile.discord-link.destroy');

    Route::prefix('admin')->middleware('can:access-admin')->name('admin.')->group(function () {
        Route::get('/', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('/overview/state', [AdminDashboardController::class, 'state'])->middleware('admin.section:overview')->name('overview.state');
        Route::get('/users', [UserAdminController::class, 'index'])->middleware('admin.section:users')->name('users.index');
        Route::patch('/users/{user}', [UserAdminController::class, 'update'])->middleware('admin.section:users')->name('users.update');
        Route::delete('/users/{user}', [UserAdminController::class, 'destroy'])->middleware('admin.section:users')->name('users.destroy');
        Route::get('/characters', [CharacterAdminController::class, 'index'])->middleware('admin.section:characters')->name('characters.index');
        Route::patch('/characters/{character}', [CharacterAdminController::class, 'update'])->middleware('admin.section:characters')->name('characters.update');
        Route::delete('/characters/{character}', [CharacterAdminController::class, 'destroy'])->middleware('admin.section:characters')->name('characters.destroy');
        Route::get('/refunds', [RefundAdminController::class, 'index'])->middleware('admin.section:refunds')->name('refunds.index');
        Route::post('/refunds', [RefundAdminController::class, 'store'])->middleware('admin.section:refunds')->name('refunds.store');
        Route::get('/character-log', [CharacterLogAdminController::class, 'index'])->middleware('admin.section:characters')->name('character-log.index');
        Route::get('/character-logs', [CharacterLogAdminController::class, 'index'])->middleware('admin.section:characters')->name('character-logs.index');
        Route::get('/nation-logs', [NationLogAdminController::class, 'index'])->middleware('admin.section:characters')->name('nation-logs.index');
        Route::get('/factions', [FactionAdminController::class, 'index'])->middleware('admin.section:factions')->name('factions.index');
        Route::post('/factions', [FactionAdminController::class, 'store'])->middleware('admin.section:factions')->name('factions.store');
        Route::patch('/factions/{faction}', [FactionAdminController::class, 'update'])->middleware('admin.section:factions')->name('factions.update');
        Route::delete('/factions/{faction}', [FactionAdminController::class, 'destroy'])->middleware('admin.section:factions')->name('factions.destroy');
        Route::get('/cities', [CityAdminController::class, 'index'])->middleware('admin.section:cities')->name('cities.index');
        Route::post('/cities', [CityAdminController::class, 'store'])->middleware('admin.section:cities')->name('cities.store');
        Route::patch('/cities/{city}', [CityAdminController::class, 'update'])->middleware('admin.section:cities')->name('cities.update');
        Route::delete('/cities/{city}', [CityAdminController::class, 'destroy'])->middleware('admin.section:cities')->name('cities.destroy');
        Route::get('/locations', [LocationAdminController::class, 'index'])->middleware('admin.section:locations')->name('locations.index');
        Route::post('/locations', [LocationAdminController::class, 'store'])->middleware('admin.section:locations')->name('locations.store');
        Route::patch('/locations/{location}', [LocationAdminController::class, 'update'])->middleware('admin.section:locations')->name('locations.update');
        Route::delete('/locations/{location}', [LocationAdminController::class, 'destroy'])->middleware('admin.section:locations')->name('locations.destroy');
        Route::get('/items', [ItemAdminController::class, 'index'])->middleware('admin.section:items')->name('items.index');
        Route::post('/items', [ItemAdminController::class, 'store'])->middleware('admin.section:items')->name('items.store');
        Route::patch('/items/{item}', [ItemAdminController::class, 'update'])->middleware('admin.section:items')->name('items.update');
        Route::delete('/items/{item}', [ItemAdminController::class, 'destroy'])->middleware('admin.section:items')->name('items.destroy');
        Route::post('/licences', [LicenceAdminController::class, 'store'])->middleware('admin.section:items')->name('licences.store');
        Route::patch('/licences/{licence}', [LicenceAdminController::class, 'update'])->middleware('admin.section:items')->name('licences.update');
        Route::delete('/licences/{licence}', [LicenceAdminController::class, 'destroy'])->middleware('admin.section:items')->name('licences.destroy');
        Route::get('/permissions', [PermissionAdminController::class, 'index'])->middleware('admin.section:permissions')->name('permissions.index');
        Route::post('/permissions', [PermissionAdminController::class, 'store'])->middleware('admin.section:permissions')->name('permissions.store');
        Route::patch('/permissions/{permission}', [PermissionAdminController::class, 'update'])->middleware('admin.section:permissions')->name('permissions.update');
        Route::delete('/permissions/{permission}', [PermissionAdminController::class, 'destroy'])->middleware('admin.section:permissions')->name('permissions.destroy');
        Route::get('/jobs', [GameJobAdminController::class, 'index'])->middleware('admin.section:jobs')->name('jobs.index');
        Route::post('/jobs', [GameJobAdminController::class, 'store'])->middleware('admin.section:jobs')->name('jobs.store');
        Route::patch('/jobs/{gameJob}', [GameJobAdminController::class, 'update'])->middleware('admin.section:jobs')->name('jobs.update');
        Route::delete('/jobs/{gameJob}', [GameJobAdminController::class, 'destroy'])->middleware('admin.section:jobs')->name('jobs.destroy');
        Route::get('/skirmishes', [SkirmishAdminController::class, 'index'])->middleware('admin.section:skirmishes')->name('skirmishes.index');
        Route::post('/skirmishes', [SkirmishAdminController::class, 'store'])->middleware('admin.section:skirmishes')->name('skirmishes.store');
        Route::patch('/skirmishes/{skirmish}', [SkirmishAdminController::class, 'update'])->middleware('admin.section:skirmishes')->name('skirmishes.update');
        Route::delete('/skirmishes/{skirmish}', [SkirmishAdminController::class, 'destroy'])->middleware('admin.section:skirmishes')->name('skirmishes.destroy');
        Route::get('/units', [UnitAdminController::class, 'index'])->middleware('admin.section:units')->name('units.index');
        Route::post('/units', [UnitAdminController::class, 'store'])->middleware('admin.section:units')->name('units.store');
        Route::patch('/units/{unit}', [UnitAdminController::class, 'update'])->middleware('admin.section:units')->name('units.update');
        Route::delete('/units/{unit}', [UnitAdminController::class, 'destroy'])->middleware('admin.section:units')->name('units.destroy');
        Route::get('/map-markers', [MapMarkerAdminController::class, 'index'])->middleware('admin.section:map_markers')->name('map-markers.index');
        Route::post('/map-markers', [MapMarkerAdminController::class, 'store'])->middleware('admin.section:map_markers')->name('map-markers.store');
        Route::patch('/map-markers/{mapMarker}', [MapMarkerAdminController::class, 'update'])->middleware('admin.section:map_markers')->name('map-markers.update');
        Route::delete('/map-markers/{mapMarker}', [MapMarkerAdminController::class, 'destroy'])->middleware('admin.section:map_markers')->name('map-markers.destroy');
        Route::post('/map-polygons', [MapMarkerAdminController::class, 'storePolygon'])->middleware('admin.section:map_markers')->name('map-polygons.store');
        Route::patch('/map-polygons/{mapPolygon}', [MapMarkerAdminController::class, 'updatePolygon'])->middleware('admin.section:map_markers')->name('map-polygons.update');
        Route::delete('/map-polygons/{mapPolygon}', [MapMarkerAdminController::class, 'destroyPolygon'])->middleware('admin.section:map_markers')->name('map-polygons.destroy');
        Route::get('/discord', [DiscordWebhookAdminController::class, 'index'])->middleware('admin.section:discord')->name('discord.index');
        Route::post('/discord', [DiscordWebhookAdminController::class, 'store'])->middleware('admin.section:discord')->name('discord.store');
        Route::patch('/discord/{discordWebhook}', [DiscordWebhookAdminController::class, 'update'])->middleware('admin.section:discord')->name('discord.update');
        Route::delete('/discord/{discordWebhook}', [DiscordWebhookAdminController::class, 'destroy'])->middleware('admin.section:discord')->name('discord.destroy');
        Route::post('/discord/commands', [DiscordWebhookAdminController::class, 'storeCommand'])->middleware('admin.section:discord')->name('discord.commands.store');
        Route::patch('/discord/commands/{discordCommand}', [DiscordWebhookAdminController::class, 'updateCommand'])->middleware('admin.section:discord')->name('discord.commands.update');
        Route::delete('/discord/commands/{discordCommand}', [DiscordWebhookAdminController::class, 'destroyCommand'])->middleware('admin.section:discord')->name('discord.commands.destroy');
        Route::get('/discord-management', [DiscordManagementController::class, 'index'])->middleware('admin.section:discord_management')->name('discord-management.index');
        Route::get('/discord-management/roster', [DiscordManagementController::class, 'roster'])->middleware('admin.section:discord_management')->name('discord-management.roster');
        Route::get('/discord-management/commands', [DiscordManagementController::class, 'commands'])->middleware('admin.section:discord_management')->name('discord-management.commands');
        Route::post('/discord-management/categories', [DiscordManagementController::class, 'storeCategory'])->middleware('admin.section:discord_management')->name('discord-management.categories.store');
        Route::patch('/discord-management/categories/{discordRoleCategory}', [DiscordManagementController::class, 'updateCategoryDefinition'])->middleware('admin.section:discord_management')->name('discord-management.categories.update');
        Route::delete('/discord-management/categories/{discordRoleCategory}', [DiscordManagementController::class, 'destroyCategory'])->middleware('admin.section:discord_management')->name('discord-management.categories.destroy');
        Route::patch('/discord-management/roles/{discordRole}/category', [DiscordManagementController::class, 'updateRoleCategory'])->middleware('admin.section:discord_management')->name('discord-management.roles.category.update');
        Route::get('/nation-requisitions', [NationRequisitionAdminController::class, 'index'])->middleware('admin.section:nation_requisitions')->name('nation-requisitions.index');
        Route::patch('/nation-requisitions/{nationRequisition}', [NationRequisitionAdminController::class, 'update'])->middleware('admin.section:nation_requisitions')->name('nation-requisitions.update');
        Route::get('/stock-market', [StockMarketAdminController::class, 'index'])->middleware('admin.section:stock_market')->name('stock-market.index');
        Route::patch('/stock-market', [StockMarketAdminController::class, 'update'])->middleware('admin.section:stock_market')->name('stock-market.update');
        Route::get('/game-master', [GameMasterAdminController::class, 'index'])->middleware('admin.section:game_master')->name('game-master.index');
        Route::post('/game-master/events', [GameMasterAdminController::class, 'store'])->middleware('admin.section:game_master')->name('game-master.events.store');
        Route::patch('/game-master/events/{gameEvent}', [GameMasterAdminController::class, 'update'])->middleware('admin.section:game_master')->name('game-master.events.update');
        Route::get('/moderator', [ModeratorAdminController::class, 'index'])->middleware('admin.section:moderator')->name('moderator.index');
    });
});

require __DIR__.'/auth.php';
